CREATE TABLE Actors
(Id INT IDENTITY(1,1) PRIMARY KEY,
Name NVARCHAR(100),
Sex NVARCHAR(10),
DOB DATE,
Bio NVARCHAR(255),
CreatedAt  DATETIME DEFAULT CURRENT_TIMESTAMP,
UpdatedAt  DATETIME DEFAULT CURRENT_TIMESTAMP)

CREATE TABLE Producers
(Id INT IDENTITY(1,1) PRIMARY KEY,
Name NVARCHAR(30),
Sex NVARCHAR(10),
DOB DATE,
Bio NVARCHAR(255),
CreatedAt  DATETIME DEFAULT CURRENT_TIMESTAMP,
UpdatedAt  DATETIME DEFAULT CURRENT_TIMESTAMP)

CREATE TABLE Genres
(Id INT IDENTITY(1,1) PRIMARY KEY,
Name NVARCHAR(30),
CreatedAt  DATETIME DEFAULT CURRENT_TIMESTAMP,
UpdatedAt  DATETIME DEFAULT CURRENT_TIMESTAMP)

CREATE TABLE Movies
( Id INT IDENTITY(1,1) PRIMARY KEY,
Name NVARCHAR(30),
YearOfRelease DATE,
Plot NVARCHAR(255),
Poster NVARCHAR(500),
ProducerId INT FOREIGN KEY REFERENCES Producers(Id),
CreatedAt  DATETIME DEFAULT CURRENT_TIMESTAMP,
UpdatedAt  DATETIME DEFAULT CURRENT_TIMESTAMP)

CREATE TABLE ActorMovieMapping
(Id INT IDENTITY(1,1) PRIMARY KEY,
ActorId INT FOREIGN KEY REFERENCES Actors(Id),
MovieId INT FOREIGN KEY REFERENCES Movies(Id),
CreatedAt  DATETIME DEFAULT CURRENT_TIMESTAMP,
UpdatedAt  DATETIME DEFAULT CURRENT_TIMESTAMP)

CREATE TABLE MovieGenreMapping
(Id INT IDENTITY(1,1) PRIMARY KEY,
MovieId INT FOREIGN KEY REFERENCES Movies(Id),
GenreID INT FOREIGN KEY REFERENCES Genres(Id),
CreatedAt  DATETIME DEFAULT CURRENT_TIMESTAMP,
UpdatedAt  DATETIME DEFAULT CURRENT_TIMESTAMP)
GO

-- Triggers for update
CREATE TRIGGER Actor_update on Actors FOR UPDATE AS
BEGIN
  UPDATE Actors
	SET UpdatedAt = GETDATE()
	FROM Actors INNER JOIN Deleted D
	on Actors.Id=D.Id
END
GO

CREATE TRIGGER Producer_update on Producers FOR UPDATE AS
BEGIN
  UPDATE Producers
	SET UpdatedAt = GETDATE()
	FROM Producers INNER JOIN Deleted D
	on Producers.Id=D.Id
END
GO

CREATE TRIGGER Movie_update on Movies FOR UPDATE AS
BEGIN
  UPDATE Movies
	SET UpdatedAt = GETDATE()
	FROM Movies INNER JOIN Deleted D
	on Movies.Id=D.Id
END
GO 

CREATE TRIGGER Genre_update on Genres FOR UPDATE AS
BEGIN
  UPDATE Genres
	SET UpdatedAt = GETDATE()
	FROM Genres INNER JOIN Deleted D
	on Genres.Id=D.Id
END
GO

CREATE TRIGGER ActorMovieMapping_update on ActorMovieMapping FOR UPDATE AS
BEGIN
  UPDATE ActorMovieMapping
	SET UpdatedAt = GETDATE()
	FROM ActorMovieMapping INNER JOIN Deleted D
	on ActorMovieMapping.Id=D.Id
END
GO

CREATE TRIGGER MovieGenreMapping_update on MovieGenreMapping FOR UPDATE AS
BEGIN
  UPDATE MovieGenreMapping
	SET UpdatedAt = GETDATE()
	FROM MovieGenreMapping INNER JOIN Deleted D
	on MovieGenreMapping.Id=D.Id
END
GO